<?php /* @var $this Cm_Diehard_Block_Afterbodystart */ ?>
<?php if(Mage::registry('diehard') && Mage::registry('diehard')->useAjax()): ?>
<script type="text/javascript">
    var fullPageCache = new FullPageCache('<?php echo $this->getPhoneUrl() ?>', '<?php echo $this->getAction()->getFullActionName() ?>');
    <?php if ($_product = Mage::registry('product')) : ?>
    fullPageCache.setParam('product_id', <?php echo (int) $_product->getId() ?>);
    <?php endif; ?>
</script>
<?php endif; ?>
