<?php /* @var $this Cm_Diehard_Block_Beforebodyend */ ?>
<?php if ( ! $this->diehard()) return; ?>
<?php if ($this->diehard()->useAjax()): ?>
<script type="text/javascript">
//<![CDATA[
    var diehard = new Diehard('<?php echo $this->getLoadAjaxUrl() ?>', '<?php echo $this->getAction()->getFullActionName() ?>');
    diehard.setParams(<?php echo json_encode($this->diehard()->getDynamicParams()) ?>);
    diehard.setBlocks(<?php echo json_encode($this->diehard()->getDynamicBlocks()) ?>);
//]]>
</script>
<?php elseif ($this->diehard()->useEsi()): ?>
<!--esi <esi:include src="<?php echo $this->getLoadEsiUrl() ?>" /> -->
<?php elseif ($this->diehard()->useJs()): /* Used for direct inline replacement */ ?>
<!-- ###DIEHARD:<?php echo json_encode($this->getDynamicParamsCombined()) ?>### -->
<?php endif; ?>
